### ISSUE TITLE
error while running  nodejs game.js

### ISSUE THREAD

**Issue by sayan801** [robhawkes/mozilla-festival#3]
root@html5:~/mozilla-festival# nodejs game.js

/root/mozilla-festival/game.js:27
        socket.configure(function() {
               ^
TypeError: Object #<Server> has no method 'configure'
    at init (/root/mozilla-festival/game.js:27:9)
    at Object.<anonymous> (/root/mozilla-festival/game.js:139:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
root@html5:~/mozilla-festival#

**Comment by Azunyan-** [comment]
I got the same error, I think socket.io changed how the configure works but I'm not sure.

**Comment by georules** [comment]
socketio changed their API since this project was made.  Here is a fix in a pull request.

https://github.com/robhawkes/mozilla-festival/pull/4

Also note that the files in public are not served by the server, you can open index.html directly from the file system, or you will need to set up some other server to host public/
